### ISSUE TITLE
BUILD BUG[Verifier bot(1872639289) failed.]

### ISSUE THREAD

**Issue by huzai9527** [HuPeng333/QQSignBot#2]
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/33509974/158309595-a849fce3-d20c-4cc3-aa05-9e555002babb.png">
- 报错如上,但是我的bot信息已经写入config

**Comment by HuPeng333** [comment]
试一下把pom.xml的`simbot.version`的值改成`2.3.8`试试？

**Comment by huzai9527** [comment]
这个问题我已经解决,但是我发现另一个问题,提醒为打卡功能貌似不可用

**Comment by huzai9527** [comment]
这个问题貌似还是由于device.json的问题,我尝试使用[TxCaptchaHelper](https://github.com/mzdluo123/TxCaptchaHelper)可以解决这个问题,然后重新编译可以跑起来

**Comment by huzai9527** [comment]
我看了一下源码,他好像 是必须打过卡的用户才能 纳入计算

**Comment by HuPeng333** [comment]
用那个'初始化群组'指令就可以把所有人加进来了

**Comment by huzai9527** [comment]
好的,感谢,这个是可以的,我在本地将last_sign字段初始化为 [昨天] 这样初始化之后就能立刻进行打卡提醒
